#!/bin/sh
# Try to find a terminal emulator that's installed and run it.

for terminal in x-terminal-emulator 'gnome-terminal --wait' xfce4-terminal konsole urxvt rxvt termit terminator Eterm aterm roxterm termite lxterminal mate-terminal terminology st xterm; do
    # bogus warning from ShellCheck < 0.5.0
    # shellcheck disable=SC2039
    if type "${terminal%%[$IFS]*}" >/dev/null 2>&1 ; then
        # shellcheck disable=SC2086
        exec $terminal
    fi
done

echo "ERROR: No suitable terminal found." >&2
